### PR TITLE
Make nk-android multi-abi & multi-target friendly

### PR DESCRIPTION
**Pull request by jfcg**
- Compile multiple ABIs into a single apk
- Connect your dev phone, run your emulator simultaneously: deploy to any
- Cleanup

### CODE REVIEW

**Comment by jfcg** [comment]
Hi @xlab, have you seen this PR ?

**Comment by xlab** [comment]
Sorry, week been though and this PR requires pre-processing as I'd like to have that as a separate project (do not replace gles3 with gles2, etc)

**Comment by jfcg** [comment]
how about now?
with preprocessing, do you mean writing to Application.mk file?

**Comment by xlab** [comment]
@jfcg sorry by pre-processing I meant that this PR couldn't be merged right away, as it will alter the example, so I had to checkout into new branch, make the modifications (so emulator target won't collide with ARM device target at all), then merge it.

The problem with having lots of targets in a single makefile is there because these files are boilerplate, intended to be copied around and should be minimal as possible. Additional targets for x86 in ARM files not welcome for this reason.

I reviewed a3dca63, so my idea is to leave `nk-android` example as is, but add another
`cmd/nk-android-x86` that will consider x86 and emulator targets.

**Comment by xlab** [comment]
Sorry we're replacing the build process system for android-go projects, thus this PR won't be merged as it is. I'll update with more news soon.

**Pull request closed without merging**
